spring:
  application:
    name: crypto-api-v1
  datasource:
    url: jdbc:postgresql://srv814560.hstgr.cloud:5432/crypto
    username: crypto
    password: crypto-signal
  data:
    redis:
      host: srv814560.hstgr.cloud
      port: 6379
      username: default
      password: b5wmHqFBNyKZ5wH6QmKS5ejp2wBCROki
      timeout: 10000ms

logging:
  level:
    root: INFO

app:
  scheduler:
    ohlcv: false
    orderDepth: false
    aggTrade: false
    fundingRate: false
    openInterest: false
    liqidationData: false
    longShortData: false
  backfill:
    ohlcv: false
    orderDepth: false
    aggTrade: false
    fundingRate: false
    openInterest: false
    liqidationData: true
    longShortData: false
  binance:
    spot-host: https://api.binance.com
    spot-market-info-endpoint: /api/v3/exchangeInfo
    spot-kline-endpoint: /api/v3/klines
    spot-aggtrade-endpoint: /api/v3/aggTrades
    spot-funding-rate-endpoint: /api/v3/fundingRate
    futures-host: https://fapi.binance.com  
    futures-market-info-endpoint: /fapi/v1/exchangeInfo
    futures-kline-endpoint: /fapi/v1/klines
    futures-aggtrade-endpoint: /fapi/v1/aggTrades
    futures-funding-rate-endpoint: /fapi/v1/fundingRate
    futures-open-interest-endpoint: /futures/data/openInterestHist
    futures-top-long-short: /futures/data/topLongShortAccountRatio
    futures-global-long-short: /futures/data/globalLongShortAccountRatio
    book-depth-host: https://data.binance.vision/data/futures/um/daily/bookDepth/
    agg-trade-host: https://data.binance.vision/data/futures/um/daily/aggTrades/
    supported-markets:
      - FUTURES_USDT
    supported-intervals:
      - 1d
      - 1h
      - 30m
      - 15m
      - 5m
      - 1m
    supported-tokens:
      - BTCUSDT
      - ETHUSDT
      - XRPUSDT
      - SOLUSDT
      - DOGEUSDT
  coinalyze:
    supported-intervals:
      - 1min
      - 5min
      - 15min
      - 30min
      - 1hour
      - daily
    host: https://api.coinalyze.net
    future-markets: /v1/future-markets
    spot-markets: /v1/spot-markets
    liqidation-history: /v1/liquidation-history
    api-key: d6132c29-f006-40f9-9459-3f9ba2835b81