version: '3.9'

services:
  app:
    image: devaprakash/crypto-signal-api:latest
    container_name: crypto-signal-api
    ports:
      - "8085:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/crypto
      - CRYPTO_API_URL=http://crypto-api-v1:8080
    networks:
      - crypto_crypto-signal

networks:
  crypto_crypto-signal:
    external: true